---
# get engine and dwh database settings
- name: set variables
  set_fact:
    ovirt_engine_db_dump_engine_db: {}
    ovirt_engine_db_dump_dwh_db: {}

- name: slurp read engine config file
  slurp:
    src: "{{ ovirt_engine_etc_conf_path }}/10-setup-database.conf"
  register: file_content

- name: matching related DB configs
  set_fact:
   decoded_content: "{{ ((file_content['content'] | b64decode).split('\n') | select('match', 'ENGINE_DB*') | list) }}"

- name: set facts for engine variables
  set_fact:
    ovirt_engine_db_dump_engine_db: >
      {{
        ovirt_engine_db_dump_engine_db |
        combine(
          dict([ [item.partition('=')[0], item.partition('=')[2] | regex_replace('\"', '')] ])
        )
      }}
  with_items: "{{ decoded_content }}"

- name: slurp read dwh config file
  slurp:
    src: "{{ ovirt_engine_etc_conf_path }}/10-setup-dwh-database.conf"
  register: file_content
  when: ovirt_engine_db_dump_dwh == True

- name: matching related DB configs
  set_fact:
   decoded_content: "{{ ((file_content['content'] | b64decode).split('\n') | select('match', 'DWH_DB*') | list) }}"
  when: ovirt_engine_db_dump_dwh == True

- name: set facts for dwh variables
  set_fact:
    ovirt_engine_db_dump_dwh_db: >
      {{
        ovirt_engine_db_dump_dwh_db |
        combine(
          dict([ [item.partition('=')[0], item.partition('=')[2] | regex_replace('\"', '')] ])
        )
      }}
  with_items: "{{ decoded_content }}"
  when: ovirt_engine_db_dump_dwh == True

# stop engine and dwh services that it won't generate more data to database
- name: stop necessary service
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - ovirt-engine-dwhd
    - ovirt-engine

# get engine and dwh database dumps
- name: enable sudo without tty
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults *requiretty$'
    line: 'Defaults    !requiretty'

- name: process postgres actions
  include_tasks: postgres_dump.yml
  when:
    - ovirt_engine_version < '4.2'

- name: process postgres 9.5 actions
  include_tasks: postgres95_dump.yml
  when:
    - ovirt_engine_version >= '4.2'

- name: create local dir
  local_action:
    file path={{ ovirt_engine_db_dump_local_dir }} state=directory

# print variables to file
- name: print engine variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_engine_db | to_nice_yaml }}" dest="{{ ovirt_engine_db_dump_local_dir }}/engine_variables.yaml"

- name: print DWH variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_dwh_db | to_nice_yaml }}" dest="{{ ovirt_engine_db_dump_local_dir }}/dwh_variables.yaml"
  when: ovirt_engine_db_dump_dwh == True

# copy files to localhost
- name: copy engine dump to local
  fetch:
    src: "{{ pgpath.stdout }}/engine.sql"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/engine.sql"
    flat: yes

- name: copy dwh dump to local
  fetch:
    src: "{{ pgpath.stdout }}/dwh.sql"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/dwh.sql"
    flat: yes
  when: ovirt_engine_db_dump_dwh == True

# start needed services
- name: start necessary service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ovirt-engine
    - ovirt-engine-dwhd
  when: ovirt_engine_db_dump_start_services == True

# clean
- name: remove dumps from engine
  file:
    path: "{{ pgpath.stdout }}/{{ item }}.sql"
    state: absent
  with_items:
    - engine
    - dwh
