---
# get engine and dwh database settings
- name: get engine/dwh db settings
  include_tasks: get-db-facts.yml

# stop engine and dwh services that it won't generate more data to database
- name: stop necessary service
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - ovirt-engine-dwhd
    - ovirt-engine

# get engine and dwh database dumps
- name: process postgres actions
  include_tasks: postgres-dump.yml
  when:
    - ovirt_engine_version < '4.2'

- name: process postgres 9.5 actions
  include_tasks: postgres95-dump.yml
  when:
    - ovirt_engine_version >= '4.2'

- name: create local dir
  local_action:
    file path={{ ovirt_engine_db_dump_local_dir }} state=directory

# print variables to file
- name: print engine variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_engine_db | to_nice_yaml }}" dest="{{ ovirt_engine_db_dump_local_dir }}/engine_variables.yml"
  when: ovirt_engine_db_dump

- name: print DWH variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_dwh_db | to_nice_yaml }}" dest="{{ ovirt_engine_db_dump_local_dir }}/dwh_variables.yml"
  when: ovirt_engine_db_dump_dwh

# copy files to localhost
- name: copy engine dump to local
  fetch:
    src: "{{ engine_remote_dump_file | default(pgpath.stdout + '/engine.tar') }}"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/engine.tar"
    flat: yes
  when: ovirt_engine_db_dump

- name: copy dwh dump to local
  fetch:
    src: "{{ dwh_remote_dump_file | default(pgpath.stdout + '/dwh.tar') }}"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/dwh.tar"
    flat: yes
  when: ovirt_engine_db_dump_dwh

# start needed services
- name: start necessary service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ovirt-engine
    - ovirt-engine-dwhd
  when: ovirt_engine_db_dump_start_services

# clean
- name: remove dumps from engine
  file:
    path: "{{ pgpath.stdout }}/{{ item }}.tar"
    state: absent
  with_items:
    - engine
    - dwh
