---
# get engine and dwh database settings
- name: set variables
  set_fact:
    ovirt_engine_db_dump_engine_db: {}
    ovirt_engine_db_dump_dwh_db: {}

- name: grep engine variables
  shell: grep "^ENGINE_DB" {{ ovirt_engine_etc_conf_path }}/10-setup-database.conf
  register: cmd
  tags:
    - skip_ansible_lint

- name: set facts for engine variables
  set_fact:
    ovirt_engine_db_dump_engine_db: >
      {{
        ovirt_engine_db_dump_engine_db |
        combine(
          dict([ [item.partition('=')[0], item.partition('=')[2]|regex_replace('\"', '')] ])
        )
      }}
  with_items: "{{ cmd.stdout_lines|list }}"

- name: grep dwh variables
  shell: grep "^DWH_DB" {{ ovirt_engine_etc_conf_path }}/10-setup-dwh-database.conf
  register: cmd
  when: ovirt_engine_db_dump_dwh == True
  tags:
    - skip_ansible_lint

- name: set facts for dwh variables
  set_fact:
    ovirt_engine_db_dump_dwh_db: >
      {{
        ovirt_engine_db_dump_dwh_db |
        combine(
          dict([ [item.partition('=')[0], item.partition('=')[2]|regex_replace('\"', '')] ])
        )
      }}
  with_items: "{{ cmd.stdout_lines|list }}"
  when: ovirt_engine_db_dump_dwh == True

# stop engine and dwh services that it won't generate more data to database
- name: stop necessary service
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - ovirt-engine-dwhd
    - ovirt-engine

# get engine and dwh database dumps
- name: enable sudo without tty
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults *requiretty$'
    line: 'Defaults    !requiretty'

- name: get postgres path
  become: yes
  become_user: postgres
  shell: echo $HOME
  register: pgpath
  tags:
    - skip_ansible_lint

- name: create local dir
  local_action:
    file path={{ ovirt_engine_db_dump_local_dir }} state=directory

- name: get dump of engine database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE'] }}"
    target: "{{ pgpath.stdout }}/engine.sql"
    state: dump

- name: get dump of dwh database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE'] }}"
    target: "{{ pgpath.stdout }}/dwh.sql"
    state: dump
  when: ovirt_engine_db_dump_dwh == True

# print variables to file
- name: print engine variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_engine_db }}" dest="{{ ovirt_engine_db_dump_local_dir }}/engine_variables.json"

- name: print DWH variables to file
  local_action:
        copy content="{{ ovirt_engine_db_dump_dwh_db }}" dest="{{ ovirt_engine_db_dump_local_dir }}/dwh_variables.json"
  when: ovirt_engine_db_dump_dwh == True

# copy files to localhost
- name: copy engine dump to local
  fetch:
    src: "{{ pgpath.stdout }}/engine.sql"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/engine.sql"
    flat: yes

- name: copy dwh dump to local
  fetch:
    src: "{{ pgpath.stdout }}/dwh.sql"
    dest: "{{ ovirt_engine_db_dump_local_dir }}/dwh.sql"
    flat: yes
  when: ovirt_engine_db_dump_dwh == True

# start needed services
- name: start necessary service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ovirt-engine
    - ovirt-engine-dwhd
  when: ovirt_engine_db_dump_start_services == True

# clean
- name: remove dumps from engine
  file:
    path: "{{ pgpath.stdout }}/{{ item }}.sql"
    state: absent
  with_items:
    - engine
    - dwh
