- name: actions under postgres user
  become: yes
  become_user: postgres
  tags:
    - skip_ansible_lint
  block:
    - name: get postgres path
      shell: echo $HOME
      register: pgpath

    - name: get dump of engine database
      command: "scl enable rh-postgresql95 \'pg_dump {{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE'] }} -f {{ pgpath.stdout }}/engine.sql\'"

    - name: get dump of dwh database
      command: "scl enable rh-postgresql95 \'pg_dump {{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE'] }} -f {{ pgpath.stdout }}/dwh.sql\'"
