- name: actions under postgres user
  become: yes
  become_user: postgres
  block:
    - name: get postgres path
      shell: echo $HOME
      register: pgpath
      tags:
        - skip_ansible_lint

    - name: get dump of engine database
      postgresql_db:
        name: "{{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE'] }}"
        target: "{{ pgpath.stdout }}/engine.sql"
        state: dump

    - name: get dump of dwh database
      postgresql_db:
        name: "{{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE'] }}"
        target: "{{ pgpath.stdout }}/dwh.sql"
        state: dump
      when: ovirt_engine_db_dump_dwh == True
