- name: actions under postgres user
  become: yes
  become_user: postgres
  block:
    - name: get postgres path
      shell: echo $HOME
      register: pgpath

    - name: get dump of engine database
      shell: "scl enable rh-postgresql95 'pg_dump {{ ovirt_engine_db_dump_engine_db['ENGINE_DB_DATABASE'] }} -f {{ pgpath.stdout }}/engine.sql'"
      tags:
        - skip_ansible_lint

    - name: get dump of dwh database
      shell: "scl enable rh-postgresql95 'pg_dump {{ ovirt_engine_db_dump_dwh_db['DWH_DB_DATABASE'] }} -f {{ pgpath.stdout }}/dwh.sql'"
      when: ovirt_engine_db_dump_dwh
      tags:
        - skip_ansible_lint
